
Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 22

Metrics/ClassLength:
  Enabled: false

# Offense count: 1
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/lita/handlers/chatops_demo.rb'
